language: python

dist: xenial

python:
  - "3.7"

install:
  # Python deps
  - pip install --upgrade pip setuptools wheel
  - pip install slackclient

script:
  - python slack-test/bot.py

notifications:
  slack:
    rooms:
      - 'astrolabsoftware/fink-broker:${SLACK_API_TOKEN}#travis_ci'
    on_success: always # default: always
    on_failure: always # default: always
