language: python

dist: xenial

python:
  - "3.7"

install:
  # Python deps
  - pip install --upgrade pip setuptools wheel
  - pip install slackclient

script:
  - python slack-test/bot.py

notifications:
  slack:
    rooms:
      secure: mgxDZjp3FXLFLPfyIFfDjHrePGpwnVBqcJbsAfqdY+VGWLfpC1BEWSLCWCOGfoiQKUrwUAlJ488hOtHRUYXa3hCfuSzkQBDcM4TQ2IvEwt50FpRgRED9XM7srzCqhpIGhr9BMZvafMops/PeKJUxYj1aH2vIG1QRZD6cVzIgi2rBoflbPPlvdgLYACKcFevsl5Xa9p7S71yX7P0Ibv5bdiUuW170Hzsxj/EVQKH01qJ10mBVLQ85pFdBwB5QLDr4gAePRfoMn74sWXvK9Zmbe8mR/AW7A7bxOy0MDXO9M9ho067XxnGSM7ZpaAcSvzKZMrv+l+8AYTiA4k9VZBLqpCFCyRkfsjd2OUeha8v0+EKyMr45pYdAtE3ao/vuHqaEEIv+hNhtjf3cxCqW4cCtl0s3fWq+z3yZaiwnT0e+M2hJvf1JIPtKf9Uoo3T7KGMSFuqLDzL5kWWc6HrZwUpbVNzWfJp5o6pcxj35r91WH12GDiDqMeXWSo1b8DCD1G0XC3IqzU2v+10gJVPAu4zeSD2yxgXp6jSbYzCSNi16LrcxxVJBfAXDp9pThMbF5T9MxZoAdVlwmxJ6pSWYkAcpYMbGPgRhG1LiiHfy/VTrvYcskKxCFffDFb9exlaqib1PyR8hxg3w3mqqIpc3NeksuLARxrcJBnFPka3v9LLZJL8=
    on_success: always # default: always
    on_failure: always # default: always
